// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZc18gnWQo5EQ1FMrTYvsFRsNPAvuz37M',
    appId: '1:159173503694:web:86765d5772a19946ce7e9f',
    messagingSenderId: '159173503694',
    projectId: 'contacts-app-429f3',
    authDomain: 'contacts-app-429f3.firebaseapp.com',
    storageBucket: 'contacts-app-429f3.firebasestorage.app',
    measurementId: 'G-R8DLF2B87G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxZAdVtIH0_4K0axgqvArSRCpx45oOAEw',
    appId: '1:159173503694:android:d5b8798140eb859bce7e9f',
    messagingSenderId: '159173503694',
    projectId: 'contacts-app-429f3',
    storageBucket: 'contacts-app-429f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY5bXTbrUYtgCUBi-luU_rAuky_ODsMCM',
    appId: '1:159173503694:ios:24c91e17b3007bbcce7e9f',
    messagingSenderId: '159173503694',
    projectId: 'contacts-app-429f3',
    storageBucket: 'contacts-app-429f3.firebasestorage.app',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY5bXTbrUYtgCUBi-luU_rAuky_ODsMCM',
    appId: '1:159173503694:ios:24c91e17b3007bbcce7e9f',
    messagingSenderId: '159173503694',
    projectId: 'contacts-app-429f3',
    storageBucket: 'contacts-app-429f3.firebasestorage.app',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZc18gnWQo5EQ1FMrTYvsFRsNPAvuz37M',
    appId: '1:159173503694:web:39d42cc13ae2410bce7e9f',
    messagingSenderId: '159173503694',
    projectId: 'contacts-app-429f3',
    authDomain: 'contacts-app-429f3.firebaseapp.com',
    storageBucket: 'contacts-app-429f3.firebasestorage.app',
    measurementId: 'G-S5EMQYLCC2',
  );
}
